version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  
conda:
  environment: environment.yaml
  
sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false
