name: tudat-docs
channels:
  - conda-forge
dependencies:
  - python
  - sphinx
  - sphinx_rtd_theme
  - sphinx-panels
  - sphinx-tabs
  - sphinx-copybutton
  - sphinx-gallery=0.10.1
  - ipython
  - ipykernel
  - ipympl
  - pandoc
  - pip
  - pip:
    - rtcat_sphinx_theme
    - sphinxcontrib-contentui
    - nbsphinx

